<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NationalitiesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('nationalities')->delete();
        
        \DB::table('nationalities')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Afghanistan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '93',
                'iso2' => 'AF',
                'iso3' => 'AFG',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Aland Islands',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '358',
                'iso2' => 'AX',
                'iso3' => 'ALA',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Albania',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '355',
                'iso2' => 'AL',
                'iso3' => 'ALB',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Algeria',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '213',
                'iso2' => 'DZ',
                'iso3' => 'DZA',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'American Samoa',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '1',
                'iso2' => 'AS',
                'iso3' => 'ASM',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Andorra',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '376',
                'iso2' => 'AD',
                'iso3' => 'AND',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Angola',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '244',
                'iso2' => 'AO',
                'iso3' => 'AGO',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Anguilla',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'AI',
                'iso3' => 'AIA',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Antarctica',
                'status' => 1,
                'region' => 'Polar',
                'subregion' => '',
                'phone_code' => '672',
                'iso2' => 'AQ',
                'iso3' => 'ATA',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Antigua And Barbuda',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'AG',
                'iso3' => 'ATG',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Argentina',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '54',
                'iso2' => 'AR',
                'iso3' => 'ARG',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Armenia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '374',
                'iso2' => 'AM',
                'iso3' => 'ARM',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Aruba',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '297',
                'iso2' => 'AW',
                'iso3' => 'ABW',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Australia',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'phone_code' => '61',
                'iso2' => 'AU',
                'iso3' => 'AUS',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Austria',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '43',
                'iso2' => 'AT',
                'iso3' => 'AUT',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Azerbaijan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '994',
                'iso2' => 'AZ',
                'iso3' => 'AZE',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Bahrain',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '973',
                'iso2' => 'BH',
                'iso3' => 'BHR',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Bangladesh',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '880',
                'iso2' => 'BD',
                'iso3' => 'BGD',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Barbados',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'BB',
                'iso3' => 'BRB',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Belarus',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '375',
                'iso2' => 'BY',
                'iso3' => 'BLR',
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Belgium',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '32',
                'iso2' => 'BE',
                'iso3' => 'BEL',
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'Belize',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '501',
                'iso2' => 'BZ',
                'iso3' => 'BLZ',
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'Benin',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '229',
                'iso2' => 'BJ',
                'iso3' => 'BEN',
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'Bermuda',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '1',
                'iso2' => 'BM',
                'iso3' => 'BMU',
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'Bhutan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '975',
                'iso2' => 'BT',
                'iso3' => 'BTN',
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'Bolivia',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '591',
                'iso2' => 'BO',
                'iso3' => 'BOL',
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'Bonaire, Sint Eustatius and Saba',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '599',
                'iso2' => 'BQ',
                'iso3' => 'BES',
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'Bosnia and Herzegovina',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '387',
                'iso2' => 'BA',
                'iso3' => 'BIH',
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'Botswana',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '267',
                'iso2' => 'BW',
                'iso3' => 'BWA',
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'Bouvet Island',
                'status' => 1,
                'region' => '',
                'subregion' => '',
                'phone_code' => '0055',
                'iso2' => 'BV',
                'iso3' => 'BVT',
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'Brazil',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '55',
                'iso2' => 'BR',
                'iso3' => 'BRA',
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'British Indian Ocean Territory',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '246',
                'iso2' => 'IO',
                'iso3' => 'IOT',
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'Brunei',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '673',
                'iso2' => 'BN',
                'iso3' => 'BRN',
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'Bulgaria',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '359',
                'iso2' => 'BG',
                'iso3' => 'BGR',
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'Burkina Faso',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '226',
                'iso2' => 'BF',
                'iso3' => 'BFA',
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'Burundi',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '257',
                'iso2' => 'BI',
                'iso3' => 'BDI',
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'Cambodia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '855',
                'iso2' => 'KH',
                'iso3' => 'KHM',
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'Cameroon',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '237',
                'iso2' => 'CM',
                'iso3' => 'CMR',
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'Canada',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '1',
                'iso2' => 'CA',
                'iso3' => 'CAN',
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'Cape Verde',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '238',
                'iso2' => 'CV',
                'iso3' => 'CPV',
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'Cayman Islands',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'KY',
                'iso3' => 'CYM',
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'Central African Republic',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '236',
                'iso2' => 'CF',
                'iso3' => 'CAF',
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'Chad',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '235',
                'iso2' => 'TD',
                'iso3' => 'TCD',
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'Chile',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '56',
                'iso2' => 'CL',
                'iso3' => 'CHL',
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'China',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '86',
                'iso2' => 'CN',
                'iso3' => 'CHN',
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'Christmas Island',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'phone_code' => '61',
                'iso2' => 'CX',
                'iso3' => 'CXR',
            ),
            46 => 
            array (
                'id' => 47,
            'name' => 'Cocos (Keeling) Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'phone_code' => '61',
                'iso2' => 'CC',
                'iso3' => 'CCK',
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'Colombia',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '57',
                'iso2' => 'CO',
                'iso3' => 'COL',
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'Comoros',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '269',
                'iso2' => 'KM',
                'iso3' => 'COM',
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'Congo',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '242',
                'iso2' => 'CG',
                'iso3' => 'COG',
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'Cook Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '682',
                'iso2' => 'CK',
                'iso3' => 'COK',
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'Costa Rica',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '506',
                'iso2' => 'CR',
                'iso3' => 'CRI',
            ),
            52 => 
            array (
                'id' => 53,
            'name' => 'Cote D\'Ivoire (Ivory Coast)',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '225',
                'iso2' => 'CI',
                'iso3' => 'CIV',
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'Croatia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '385',
                'iso2' => 'HR',
                'iso3' => 'HRV',
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'Cuba',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '53',
                'iso2' => 'CU',
                'iso3' => 'CUB',
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'Curaçao',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '599',
                'iso2' => 'CW',
                'iso3' => 'CUW',
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'Cyprus',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '357',
                'iso2' => 'CY',
                'iso3' => 'CYP',
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'Czech Republic',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '420',
                'iso2' => 'CZ',
                'iso3' => 'CZE',
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'Democratic Republic of the Congo',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '243',
                'iso2' => 'CD',
                'iso3' => 'COD',
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'Denmark',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '45',
                'iso2' => 'DK',
                'iso3' => 'DNK',
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'Djibouti',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '253',
                'iso2' => 'DJ',
                'iso3' => 'DJI',
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'Dominica',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'DM',
                'iso3' => 'DMA',
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'Dominican Republic',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'DO',
                'iso3' => 'DOM',
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'East Timor',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '670',
                'iso2' => 'TL',
                'iso3' => 'TLS',
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'Ecuador',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '593',
                'iso2' => 'EC',
                'iso3' => 'ECU',
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'Egypt',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '20',
                'iso2' => 'EG',
                'iso3' => 'EGY',
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'El Salvador',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '503',
                'iso2' => 'SV',
                'iso3' => 'SLV',
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'Equatorial Guinea',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '240',
                'iso2' => 'GQ',
                'iso3' => 'GNQ',
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'Eritrea',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '291',
                'iso2' => 'ER',
                'iso3' => 'ERI',
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'Estonia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '372',
                'iso2' => 'EE',
                'iso3' => 'EST',
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'Ethiopia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '251',
                'iso2' => 'ET',
                'iso3' => 'ETH',
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'Falkland Islands',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '500',
                'iso2' => 'FK',
                'iso3' => 'FLK',
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'Faroe Islands',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '298',
                'iso2' => 'FO',
                'iso3' => 'FRO',
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'Fiji Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'phone_code' => '679',
                'iso2' => 'FJ',
                'iso3' => 'FJI',
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'Finland',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '358',
                'iso2' => 'FI',
                'iso3' => 'FIN',
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'France',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '33',
                'iso2' => 'FR',
                'iso3' => 'FRA',
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'French Guiana',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '594',
                'iso2' => 'GF',
                'iso3' => 'GUF',
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'French Polynesia',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '689',
                'iso2' => 'PF',
                'iso3' => 'PYF',
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'French Southern Territories',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '262',
                'iso2' => 'TF',
                'iso3' => 'ATF',
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'Gabon',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '241',
                'iso2' => 'GA',
                'iso3' => 'GAB',
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'Gambia The',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '220',
                'iso2' => 'GM',
                'iso3' => 'GMB',
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'Georgia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '995',
                'iso2' => 'GE',
                'iso3' => 'GEO',
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'Germany',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '49',
                'iso2' => 'DE',
                'iso3' => 'DEU',
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'Ghana',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '233',
                'iso2' => 'GH',
                'iso3' => 'GHA',
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'Gibraltar',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '350',
                'iso2' => 'GI',
                'iso3' => 'GIB',
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'Greece',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '30',
                'iso2' => 'GR',
                'iso3' => 'GRC',
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'Greenland',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '299',
                'iso2' => 'GL',
                'iso3' => 'GRL',
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'Grenada',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'GD',
                'iso3' => 'GRD',
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'Guadeloupe',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '590',
                'iso2' => 'GP',
                'iso3' => 'GLP',
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'Guam',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '1',
                'iso2' => 'GU',
                'iso3' => 'GUM',
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'Guatemala',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '502',
                'iso2' => 'GT',
                'iso3' => 'GTM',
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'Guernsey and Alderney',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '44',
                'iso2' => 'GG',
                'iso3' => 'GGY',
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'Guinea',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '224',
                'iso2' => 'GN',
                'iso3' => 'GIN',
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'Guinea-Bissau',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '245',
                'iso2' => 'GW',
                'iso3' => 'GNB',
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'Guyana',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '592',
                'iso2' => 'GY',
                'iso3' => 'GUY',
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'Haiti',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '509',
                'iso2' => 'HT',
                'iso3' => 'HTI',
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'Heard Island and McDonald Islands',
                'status' => 1,
                'region' => '',
                'subregion' => '',
                'phone_code' => '672',
                'iso2' => 'HM',
                'iso3' => 'HMD',
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'Honduras',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '504',
                'iso2' => 'HN',
                'iso3' => 'HND',
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'Hong Kong S.A.R.',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '852',
                'iso2' => 'HK',
                'iso3' => 'HKG',
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'Hungary',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '36',
                'iso2' => 'HU',
                'iso3' => 'HUN',
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'Iceland',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '354',
                'iso2' => 'IS',
                'iso3' => 'ISL',
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'India',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '91',
                'iso2' => 'IN',
                'iso3' => 'IND',
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'Indonesia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '62',
                'iso2' => 'ID',
                'iso3' => 'IDN',
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'Iran',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '98',
                'iso2' => 'IR',
                'iso3' => 'IRN',
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'Iraq',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '964',
                'iso2' => 'IQ',
                'iso3' => 'IRQ',
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'Ireland',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '353',
                'iso2' => 'IE',
                'iso3' => 'IRL',
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'Israel',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '972',
                'iso2' => 'IL',
                'iso3' => 'ISR',
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'Italy',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '39',
                'iso2' => 'IT',
                'iso3' => 'ITA',
            ),
            108 => 
            array (
                'id' => 109,
                'name' => 'Jamaica',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'JM',
                'iso3' => 'JAM',
            ),
            109 => 
            array (
                'id' => 110,
                'name' => 'Japan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '81',
                'iso2' => 'JP',
                'iso3' => 'JPN',
            ),
            110 => 
            array (
                'id' => 111,
                'name' => 'Jersey',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '44',
                'iso2' => 'JE',
                'iso3' => 'JEY',
            ),
            111 => 
            array (
                'id' => 112,
                'name' => 'Jordan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '962',
                'iso2' => 'JO',
                'iso3' => 'JOR',
            ),
            112 => 
            array (
                'id' => 113,
                'name' => 'Kazakhstan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'phone_code' => '7',
                'iso2' => 'KZ',
                'iso3' => 'KAZ',
            ),
            113 => 
            array (
                'id' => 114,
                'name' => 'Kenya',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '254',
                'iso2' => 'KE',
                'iso3' => 'KEN',
            ),
            114 => 
            array (
                'id' => 115,
                'name' => 'Kiribati',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '686',
                'iso2' => 'KI',
                'iso3' => 'KIR',
            ),
            115 => 
            array (
                'id' => 116,
                'name' => 'Kosovo',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '383',
                'iso2' => 'XK',
                'iso3' => 'XKX',
            ),
            116 => 
            array (
                'id' => 117,
                'name' => 'Kuwait',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '965',
                'iso2' => 'KW',
                'iso3' => 'KWT',
            ),
            117 => 
            array (
                'id' => 118,
                'name' => 'Kyrgyzstan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'phone_code' => '996',
                'iso2' => 'KG',
                'iso3' => 'KGZ',
            ),
            118 => 
            array (
                'id' => 119,
                'name' => 'Laos',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '856',
                'iso2' => 'LA',
                'iso3' => 'LAO',
            ),
            119 => 
            array (
                'id' => 120,
                'name' => 'Latvia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '371',
                'iso2' => 'LV',
                'iso3' => 'LVA',
            ),
            120 => 
            array (
                'id' => 121,
                'name' => 'Lebanon',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '961',
                'iso2' => 'LB',
                'iso3' => 'LBN',
            ),
            121 => 
            array (
                'id' => 122,
                'name' => 'Lesotho',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '266',
                'iso2' => 'LS',
                'iso3' => 'LSO',
            ),
            122 => 
            array (
                'id' => 123,
                'name' => 'Liberia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '231',
                'iso2' => 'LR',
                'iso3' => 'LBR',
            ),
            123 => 
            array (
                'id' => 124,
                'name' => 'Libya',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '218',
                'iso2' => 'LY',
                'iso3' => 'LBY',
            ),
            124 => 
            array (
                'id' => 125,
                'name' => 'Liechtenstein',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '423',
                'iso2' => 'LI',
                'iso3' => 'LIE',
            ),
            125 => 
            array (
                'id' => 126,
                'name' => 'Lithuania',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '370',
                'iso2' => 'LT',
                'iso3' => 'LTU',
            ),
            126 => 
            array (
                'id' => 127,
                'name' => 'Luxembourg',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '352',
                'iso2' => 'LU',
                'iso3' => 'LUX',
            ),
            127 => 
            array (
                'id' => 128,
                'name' => 'Macau S.A.R.',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '853',
                'iso2' => 'MO',
                'iso3' => 'MAC',
            ),
            128 => 
            array (
                'id' => 129,
                'name' => 'Macedonia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '389',
                'iso2' => 'MK',
                'iso3' => 'MKD',
            ),
            129 => 
            array (
                'id' => 130,
                'name' => 'Madagascar',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '261',
                'iso2' => 'MG',
                'iso3' => 'MDG',
            ),
            130 => 
            array (
                'id' => 131,
                'name' => 'Malawi',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '265',
                'iso2' => 'MW',
                'iso3' => 'MWI',
            ),
            131 => 
            array (
                'id' => 132,
                'name' => 'Malaysia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '60',
                'iso2' => 'MY',
                'iso3' => 'MYS',
            ),
            132 => 
            array (
                'id' => 133,
                'name' => 'Maldives',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '960',
                'iso2' => 'MV',
                'iso3' => 'MDV',
            ),
            133 => 
            array (
                'id' => 134,
                'name' => 'Mali',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '223',
                'iso2' => 'ML',
                'iso3' => 'MLI',
            ),
            134 => 
            array (
                'id' => 135,
                'name' => 'Malta',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '356',
                'iso2' => 'MT',
                'iso3' => 'MLT',
            ),
            135 => 
            array (
                'id' => 136,
            'name' => 'Man (Isle of)',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '44',
                'iso2' => 'IM',
                'iso3' => 'IMN',
            ),
            136 => 
            array (
                'id' => 137,
                'name' => 'Marshall Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '692',
                'iso2' => 'MH',
                'iso3' => 'MHL',
            ),
            137 => 
            array (
                'id' => 138,
                'name' => 'Martinique',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '596',
                'iso2' => 'MQ',
                'iso3' => 'MTQ',
            ),
            138 => 
            array (
                'id' => 139,
                'name' => 'Mauritania',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '222',
                'iso2' => 'MR',
                'iso3' => 'MRT',
            ),
            139 => 
            array (
                'id' => 140,
                'name' => 'Mauritius',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '230',
                'iso2' => 'MU',
                'iso3' => 'MUS',
            ),
            140 => 
            array (
                'id' => 141,
                'name' => 'Mayotte',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '262',
                'iso2' => 'YT',
                'iso3' => 'MYT',
            ),
            141 => 
            array (
                'id' => 142,
                'name' => 'Mexico',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '52',
                'iso2' => 'MX',
                'iso3' => 'MEX',
            ),
            142 => 
            array (
                'id' => 143,
                'name' => 'Micronesia',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '691',
                'iso2' => 'FM',
                'iso3' => 'FSM',
            ),
            143 => 
            array (
                'id' => 144,
                'name' => 'Moldova',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '373',
                'iso2' => 'MD',
                'iso3' => 'MDA',
            ),
            144 => 
            array (
                'id' => 145,
                'name' => 'Monaco',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '377',
                'iso2' => 'MC',
                'iso3' => 'MCO',
            ),
            145 => 
            array (
                'id' => 146,
                'name' => 'Mongolia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '976',
                'iso2' => 'MN',
                'iso3' => 'MNG',
            ),
            146 => 
            array (
                'id' => 147,
                'name' => 'Montenegro',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '382',
                'iso2' => 'ME',
                'iso3' => 'MNE',
            ),
            147 => 
            array (
                'id' => 148,
                'name' => 'Montserrat',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'MS',
                'iso3' => 'MSR',
            ),
            148 => 
            array (
                'id' => 149,
                'name' => 'Morocco',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '212',
                'iso2' => 'MA',
                'iso3' => 'MAR',
            ),
            149 => 
            array (
                'id' => 150,
                'name' => 'Mozambique',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '258',
                'iso2' => 'MZ',
                'iso3' => 'MOZ',
            ),
            150 => 
            array (
                'id' => 151,
                'name' => 'Myanmar',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '95',
                'iso2' => 'MM',
                'iso3' => 'MMR',
            ),
            151 => 
            array (
                'id' => 152,
                'name' => 'Namibia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '264',
                'iso2' => 'NA',
                'iso3' => 'NAM',
            ),
            152 => 
            array (
                'id' => 153,
                'name' => 'Nauru',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '674',
                'iso2' => 'NR',
                'iso3' => 'NRU',
            ),
            153 => 
            array (
                'id' => 154,
                'name' => 'Nepal',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '977',
                'iso2' => 'NP',
                'iso3' => 'NPL',
            ),
            154 => 
            array (
                'id' => 155,
                'name' => 'Netherlands',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '31',
                'iso2' => 'NL',
                'iso3' => 'NLD',
            ),
            155 => 
            array (
                'id' => 156,
                'name' => 'New Caledonia',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'phone_code' => '687',
                'iso2' => 'NC',
                'iso3' => 'NCL',
            ),
            156 => 
            array (
                'id' => 157,
                'name' => 'New Zealand',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'phone_code' => '64',
                'iso2' => 'NZ',
                'iso3' => 'NZL',
            ),
            157 => 
            array (
                'id' => 158,
                'name' => 'Nicaragua',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '505',
                'iso2' => 'NI',
                'iso3' => 'NIC',
            ),
            158 => 
            array (
                'id' => 159,
                'name' => 'Niger',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '227',
                'iso2' => 'NE',
                'iso3' => 'NER',
            ),
            159 => 
            array (
                'id' => 160,
                'name' => 'Nigeria',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '234',
                'iso2' => 'NG',
                'iso3' => 'NGA',
            ),
            160 => 
            array (
                'id' => 161,
                'name' => 'Niue',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '683',
                'iso2' => 'NU',
                'iso3' => 'NIU',
            ),
            161 => 
            array (
                'id' => 162,
                'name' => 'Norfolk Island',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'phone_code' => '672',
                'iso2' => 'NF',
                'iso3' => 'NFK',
            ),
            162 => 
            array (
                'id' => 163,
                'name' => 'North Korea',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '850',
                'iso2' => 'KP',
                'iso3' => 'PRK',
            ),
            163 => 
            array (
                'id' => 164,
                'name' => 'Northern Mariana Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '1',
                'iso2' => 'MP',
                'iso3' => 'MNP',
            ),
            164 => 
            array (
                'id' => 165,
                'name' => 'Norway',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '47',
                'iso2' => 'NO',
                'iso3' => 'NOR',
            ),
            165 => 
            array (
                'id' => 166,
                'name' => 'Oman',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '968',
                'iso2' => 'OM',
                'iso3' => 'OMN',
            ),
            166 => 
            array (
                'id' => 167,
                'name' => 'Pakistan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '92',
                'iso2' => 'PK',
                'iso3' => 'PAK',
            ),
            167 => 
            array (
                'id' => 168,
                'name' => 'Palau',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Micronesia',
                'phone_code' => '680',
                'iso2' => 'PW',
                'iso3' => 'PLW',
            ),
            168 => 
            array (
                'id' => 169,
                'name' => 'Palestinian Territory Occupied',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '970',
                'iso2' => 'PS',
                'iso3' => 'PSE',
            ),
            169 => 
            array (
                'id' => 170,
                'name' => 'Panama',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Central America',
                'phone_code' => '507',
                'iso2' => 'PA',
                'iso3' => 'PAN',
            ),
            170 => 
            array (
                'id' => 171,
                'name' => 'Papua new Guinea',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'phone_code' => '675',
                'iso2' => 'PG',
                'iso3' => 'PNG',
            ),
            171 => 
            array (
                'id' => 172,
                'name' => 'Paraguay',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '595',
                'iso2' => 'PY',
                'iso3' => 'PRY',
            ),
            172 => 
            array (
                'id' => 173,
                'name' => 'Peru',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '51',
                'iso2' => 'PE',
                'iso3' => 'PER',
            ),
            173 => 
            array (
                'id' => 174,
                'name' => 'Philippines',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '63',
                'iso2' => 'PH',
                'iso3' => 'PHL',
            ),
            174 => 
            array (
                'id' => 175,
                'name' => 'Pitcairn Island',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '870',
                'iso2' => 'PN',
                'iso3' => 'PCN',
            ),
            175 => 
            array (
                'id' => 176,
                'name' => 'Poland',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '48',
                'iso2' => 'PL',
                'iso3' => 'POL',
            ),
            176 => 
            array (
                'id' => 177,
                'name' => 'Portugal',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '351',
                'iso2' => 'PT',
                'iso3' => 'PRT',
            ),
            177 => 
            array (
                'id' => 178,
                'name' => 'Puerto Rico',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'PR',
                'iso3' => 'PRI',
            ),
            178 => 
            array (
                'id' => 179,
                'name' => 'Qatar',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '974',
                'iso2' => 'QA',
                'iso3' => 'QAT',
            ),
            179 => 
            array (
                'id' => 180,
                'name' => 'Reunion',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '262',
                'iso2' => 'RE',
                'iso3' => 'REU',
            ),
            180 => 
            array (
                'id' => 181,
                'name' => 'Romania',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '40',
                'iso2' => 'RO',
                'iso3' => 'ROU',
            ),
            181 => 
            array (
                'id' => 182,
                'name' => 'Russia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '7',
                'iso2' => 'RU',
                'iso3' => 'RUS',
            ),
            182 => 
            array (
                'id' => 183,
                'name' => 'Rwanda',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '250',
                'iso2' => 'RW',
                'iso3' => 'RWA',
            ),
            183 => 
            array (
                'id' => 184,
                'name' => 'Saint Helena',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '290',
                'iso2' => 'SH',
                'iso3' => 'SHN',
            ),
            184 => 
            array (
                'id' => 185,
                'name' => 'Saint Kitts And Nevis',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'KN',
                'iso3' => 'KNA',
            ),
            185 => 
            array (
                'id' => 186,
                'name' => 'Saint Lucia',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'LC',
                'iso3' => 'LCA',
            ),
            186 => 
            array (
                'id' => 187,
                'name' => 'Saint Pierre and Miquelon',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '508',
                'iso2' => 'PM',
                'iso3' => 'SPM',
            ),
            187 => 
            array (
                'id' => 188,
                'name' => 'Saint Vincent And The Grenadines',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'VC',
                'iso3' => 'VCT',
            ),
            188 => 
            array (
                'id' => 189,
                'name' => 'Saint-Barthelemy',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '590',
                'iso2' => 'BL',
                'iso3' => 'BLM',
            ),
            189 => 
            array (
                'id' => 190,
            'name' => 'Saint-Martin (French part)',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '590',
                'iso2' => 'MF',
                'iso3' => 'MAF',
            ),
            190 => 
            array (
                'id' => 191,
                'name' => 'Samoa',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '685',
                'iso2' => 'WS',
                'iso3' => 'WSM',
            ),
            191 => 
            array (
                'id' => 192,
                'name' => 'San Marino',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '378',
                'iso2' => 'SM',
                'iso3' => 'SMR',
            ),
            192 => 
            array (
                'id' => 193,
                'name' => 'Sao Tome and Principe',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '239',
                'iso2' => 'ST',
                'iso3' => 'STP',
            ),
            193 => 
            array (
                'id' => 194,
                'name' => 'Saudi Arabia',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '966',
                'iso2' => 'SA',
                'iso3' => 'SAU',
            ),
            194 => 
            array (
                'id' => 195,
                'name' => 'Senegal',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '221',
                'iso2' => 'SN',
                'iso3' => 'SEN',
            ),
            195 => 
            array (
                'id' => 196,
                'name' => 'Serbia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '381',
                'iso2' => 'RS',
                'iso3' => 'SRB',
            ),
            196 => 
            array (
                'id' => 197,
                'name' => 'Seychelles',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '248',
                'iso2' => 'SC',
                'iso3' => 'SYC',
            ),
            197 => 
            array (
                'id' => 198,
                'name' => 'Sierra Leone',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '232',
                'iso2' => 'SL',
                'iso3' => 'SLE',
            ),
            198 => 
            array (
                'id' => 199,
                'name' => 'Singapore',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '65',
                'iso2' => 'SG',
                'iso3' => 'SGP',
            ),
            199 => 
            array (
                'id' => 200,
            'name' => 'Sint Maarten (Dutch part)',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1721',
                'iso2' => 'SX',
                'iso3' => 'SXM',
            ),
            200 => 
            array (
                'id' => 201,
                'name' => 'Slovakia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '421',
                'iso2' => 'SK',
                'iso3' => 'SVK',
            ),
            201 => 
            array (
                'id' => 202,
                'name' => 'Slovenia',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '386',
                'iso2' => 'SI',
                'iso3' => 'SVN',
            ),
            202 => 
            array (
                'id' => 203,
                'name' => 'Solomon Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'phone_code' => '677',
                'iso2' => 'SB',
                'iso3' => 'SLB',
            ),
            203 => 
            array (
                'id' => 204,
                'name' => 'Somalia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '252',
                'iso2' => 'SO',
                'iso3' => 'SOM',
            ),
            204 => 
            array (
                'id' => 205,
                'name' => 'South Africa',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '27',
                'iso2' => 'ZA',
                'iso3' => 'ZAF',
            ),
            205 => 
            array (
                'id' => 206,
                'name' => 'South Georgia',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '500',
                'iso2' => 'GS',
                'iso3' => 'SGS',
            ),
            206 => 
            array (
                'id' => 207,
                'name' => 'South Korea',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '82',
                'iso2' => 'KR',
                'iso3' => 'KOR',
            ),
            207 => 
            array (
                'id' => 208,
                'name' => 'South Sudan',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Middle Africa',
                'phone_code' => '211',
                'iso2' => 'SS',
                'iso3' => 'SSD',
            ),
            208 => 
            array (
                'id' => 209,
                'name' => 'Spain',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '34',
                'iso2' => 'ES',
                'iso3' => 'ESP',
            ),
            209 => 
            array (
                'id' => 210,
                'name' => 'Sri Lanka',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'phone_code' => '94',
                'iso2' => 'LK',
                'iso3' => 'LKA',
            ),
            210 => 
            array (
                'id' => 211,
                'name' => 'Sudan',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '249',
                'iso2' => 'SD',
                'iso3' => 'SDN',
            ),
            211 => 
            array (
                'id' => 212,
                'name' => 'Suriname',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '597',
                'iso2' => 'SR',
                'iso3' => 'SUR',
            ),
            212 => 
            array (
                'id' => 213,
                'name' => 'Svalbard And Jan Mayen Islands',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '47',
                'iso2' => 'SJ',
                'iso3' => 'SJM',
            ),
            213 => 
            array (
                'id' => 214,
                'name' => 'Swaziland',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'phone_code' => '268',
                'iso2' => 'SZ',
                'iso3' => 'SWZ',
            ),
            214 => 
            array (
                'id' => 215,
                'name' => 'Sweden',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '46',
                'iso2' => 'SE',
                'iso3' => 'SWE',
            ),
            215 => 
            array (
                'id' => 216,
                'name' => 'Switzerland',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'phone_code' => '41',
                'iso2' => 'CH',
                'iso3' => 'CHE',
            ),
            216 => 
            array (
                'id' => 217,
                'name' => 'Syria',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '963',
                'iso2' => 'SY',
                'iso3' => 'SYR',
            ),
            217 => 
            array (
                'id' => 218,
                'name' => 'Taiwan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'phone_code' => '886',
                'iso2' => 'TW',
                'iso3' => 'TWN',
            ),
            218 => 
            array (
                'id' => 219,
                'name' => 'Tajikistan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'phone_code' => '992',
                'iso2' => 'TJ',
                'iso3' => 'TJK',
            ),
            219 => 
            array (
                'id' => 220,
                'name' => 'Tanzania',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '255',
                'iso2' => 'TZ',
                'iso3' => 'TZA',
            ),
            220 => 
            array (
                'id' => 221,
                'name' => 'Thailand',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '66',
                'iso2' => 'TH',
                'iso3' => 'THA',
            ),
            221 => 
            array (
                'id' => 222,
                'name' => 'The Bahamas',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'BS',
                'iso3' => 'BHS',
            ),
            222 => 
            array (
                'id' => 223,
                'name' => 'Togo',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'phone_code' => '228',
                'iso2' => 'TG',
                'iso3' => 'TGO',
            ),
            223 => 
            array (
                'id' => 224,
                'name' => 'Tokelau',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '690',
                'iso2' => 'TK',
                'iso3' => 'TKL',
            ),
            224 => 
            array (
                'id' => 225,
                'name' => 'Tonga',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '676',
                'iso2' => 'TO',
                'iso3' => 'TON',
            ),
            225 => 
            array (
                'id' => 226,
                'name' => 'Trinidad And Tobago',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'TT',
                'iso3' => 'TTO',
            ),
            226 => 
            array (
                'id' => 227,
                'name' => 'Tunisia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '216',
                'iso2' => 'TN',
                'iso3' => 'TUN',
            ),
            227 => 
            array (
                'id' => 228,
                'name' => 'Turkey',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '90',
                'iso2' => 'TR',
                'iso3' => 'TUR',
            ),
            228 => 
            array (
                'id' => 229,
                'name' => 'Turkmenistan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'phone_code' => '993',
                'iso2' => 'TM',
                'iso3' => 'TKM',
            ),
            229 => 
            array (
                'id' => 230,
                'name' => 'Turks And Caicos Islands',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'TC',
                'iso3' => 'TCA',
            ),
            230 => 
            array (
                'id' => 231,
                'name' => 'Tuvalu',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '688',
                'iso2' => 'TV',
                'iso3' => 'TUV',
            ),
            231 => 
            array (
                'id' => 232,
                'name' => 'Uganda',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '256',
                'iso2' => 'UG',
                'iso3' => 'UGA',
            ),
            232 => 
            array (
                'id' => 233,
                'name' => 'Ukraine',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'phone_code' => '380',
                'iso2' => 'UA',
                'iso3' => 'UKR',
            ),
            233 => 
            array (
                'id' => 234,
                'name' => 'United Arab Emirates',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '971',
                'iso2' => 'AE',
                'iso3' => 'ARE',
            ),
            234 => 
            array (
                'id' => 235,
                'name' => 'United Kingdom',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'phone_code' => '44',
                'iso2' => 'GB',
                'iso3' => 'GBR',
            ),
            235 => 
            array (
                'id' => 236,
                'name' => 'United States',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '1',
                'iso2' => 'US',
                'iso3' => 'USA',
            ),
            236 => 
            array (
                'id' => 237,
                'name' => 'United States Minor Outlying Islands',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Northern America',
                'phone_code' => '1',
                'iso2' => 'UM',
                'iso3' => 'UMI',
            ),
            237 => 
            array (
                'id' => 238,
                'name' => 'Uruguay',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '598',
                'iso2' => 'UY',
                'iso3' => 'URY',
            ),
            238 => 
            array (
                'id' => 239,
                'name' => 'Uzbekistan',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Central Asia',
                'phone_code' => '998',
                'iso2' => 'UZ',
                'iso3' => 'UZB',
            ),
            239 => 
            array (
                'id' => 240,
                'name' => 'Vanuatu',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Melanesia',
                'phone_code' => '678',
                'iso2' => 'VU',
                'iso3' => 'VUT',
            ),
            240 => 
            array (
                'id' => 241,
            'name' => 'Vatican City State (Holy See)',
                'status' => 1,
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'phone_code' => '379',
                'iso2' => 'VA',
                'iso3' => 'VAT',
            ),
            241 => 
            array (
                'id' => 242,
                'name' => 'Venezuela',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'South America',
                'phone_code' => '58',
                'iso2' => 'VE',
                'iso3' => 'VEN',
            ),
            242 => 
            array (
                'id' => 243,
                'name' => 'Vietnam',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'phone_code' => '84',
                'iso2' => 'VN',
                'iso3' => 'VNM',
            ),
            243 => 
            array (
                'id' => 244,
            'name' => 'Virgin Islands (British)',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'VG',
                'iso3' => 'VGB',
            ),
            244 => 
            array (
                'id' => 245,
            'name' => 'Virgin Islands (US)',
                'status' => 1,
                'region' => 'Americas',
                'subregion' => 'Caribbean',
                'phone_code' => '1',
                'iso2' => 'VI',
                'iso3' => 'VIR',
            ),
            245 => 
            array (
                'id' => 246,
                'name' => 'Wallis And Futuna Islands',
                'status' => 1,
                'region' => 'Oceania',
                'subregion' => 'Polynesia',
                'phone_code' => '681',
                'iso2' => 'WF',
                'iso3' => 'WLF',
            ),
            246 => 
            array (
                'id' => 247,
                'name' => 'Western Sahara',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'phone_code' => '212',
                'iso2' => 'EH',
                'iso3' => 'ESH',
            ),
            247 => 
            array (
                'id' => 248,
                'name' => 'Yemen',
                'status' => 1,
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'phone_code' => '967',
                'iso2' => 'YE',
                'iso3' => 'YEM',
            ),
            248 => 
            array (
                'id' => 249,
                'name' => 'Zambia',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '260',
                'iso2' => 'ZM',
                'iso3' => 'ZMB',
            ),
            249 => 
            array (
                'id' => 250,
                'name' => 'Zimbabwe',
                'status' => 1,
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'phone_code' => '263',
                'iso2' => 'ZW',
                'iso3' => 'ZWE',
            ),
        ));
        
        
    }
}