<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TenancyUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array(
            0 =>
                array(
                    'id' => 1,
                    'name' => 'Super Admin',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'superadmin@sms.com',
                    'code' => 'SUPERADMIN',
                    'username' => 'superadmin',
                    'user_type' => 'super_admin',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 81',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120781,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('superadmin'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            1 =>
                array(
                    'id' => 2,
                    'name' => 'Admin',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'admin@sms.com',
                    'code' => 'ADMIN',
                    'username' => 'admin',
                    'user_type' => 'admin',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('admin'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            2 =>
                array(
                    'id' => 3,
                    'name' => 'Teacher',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'teacher@sms.com',
                    'code' => 'TEACHER',
                    'username' => 'teacher',
                    'user_type' => 'teacher',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('teacher'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            3 =>
                array(
                    'id' => 4,
                    'name' => 'Companion',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'companion@sms.com',
                    'code' => 'COMPANION',
                    'username' => 'companion',
                    'user_type' => 'companion',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('companion'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            4 =>
                array(
                    'id' => 5,
                    'name' => 'Parent',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'parent@sms.com',
                    'code' => 'PARENT',
                    'username' => 'parent',
                    'user_type' => 'parent',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('parent'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            5 =>
                array(
                    'id' => 6,
                    'name' => 'Accountant',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'accountant@sms.com',
                    'code' => 'ACCOUNTANT',
                    'username' => 'accountant',
                    'user_type' => 'accountant',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('accountant'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            6 =>
                array(
                    'id' => 7,
                    'name' => 'Student',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'student@sms.com',
                    'code' => 'STUDENT',
                    'username' => 'student',
                    'user_type' => 'student',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('student'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
            7 =>
                array(
                    'id' => 8,
                    'name' => 'Librarian',
                    'blocked' => 0,
                    'religion' => 'Islam',
                    'email' => 'librarian@sms.com',
                    'code' => 'LIBRARIAN',
                    'username' => 'librarian',
                    'user_type' => 'librarian',
                    'work' => NULL,
                    'dob' => '01/11/1111',
                    'gender' => 'Male',
                    'photo' => 'global_assets/images/user.png',
                    'primary_id' => '',
                    'secondary_id' => '',
                    'phone' => '+255 1234 567 89',
                    'phone2' => NULL,
                    'bg_id' => 2,
                    'state_id' => 4081,
                    'lga_id' => 120780,
                    'nal_id' => 220,
                    'address' => 'address',
                    'email_verified_at' => NULL,
                    'password' => Hash::make('librarian'),
                    'remember_token' => NULL,
                    'sidebar_minimized' => 0,
                    'show_charts' => 1,
                    'password_updated_at' => NULL,
                    'twofa_secret_code' => NULL,
                    'twofa_recovery_codes' => NULL,
                    'created_at' => NULL,
                    'updated_at' => NULL,
                    'deleted_at' => NULL,
                ),
        ));
    }
}